{{- $root := . -}}
{{- include "opennebula-csi.validateDriverIdentityArgs" $root -}}
{{- range .Values.storageClasses }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}
  {{- with .annotations }}
  annotations:
{{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .labels }}
  labels:
{{ toYaml . | nindent 4 }}
  {{- end }}
provisioner: {{ include "opennebula-csi.driverName" $root }}
reclaimPolicy: {{ default "Delete" .reclaimPolicy }}
allowVolumeExpansion: {{ default false .allowVolumeExpansion }}
mountOptions:
{{- if .mountOptions }}
{{ toYaml .mountOptions | nindent 2 }}
{{- else }}
  []
{{- end }}
volumeBindingMode: {{ default "Immediate" .volumeBindingMode }}
parameters:
{{- if .parameters }}
{{ toYaml .parameters | nindent 2 }}
{{- else }}
  {}
{{- end }}
{{- end }}
